services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.13
    container_name: ${INSTALL_NODE}-etcd
    restart: always
    network_mode: host
    command: >
      /usr/local/bin/etcd
      --name=${ETCD_MEMBER_NAME}
      --data-dir=/etcd-data
      --initial-advertise-peer-urls=http://${INSTALL_NODE_IP}:${ETCD_PORT}
      --listen-peer-urls=http://${INSTALL_NODE_IP}:${ETCD_PORT}
      --listen-client-urls=http://${INSTALL_NODE_IP}:${ETCD_CLIENT_PORT},http://127.0.0.1:${ETCD_CLIENT_PORT}
      --advertise-client-urls=http://${INSTALL_NODE_IP}:${ETCD_CLIENT_PORT}
      --initial-cluster=${ETCD_PEERS}
      --initial-cluster-token=${CLUSTER_TOKEN}
      --initial-cluster-state=new
      --enable-v2=true
    volumes:
      - etcd_data:/etcd-data

  patroni:
    image: ghcr.io/zalando/spilo-17:4.0-p3
    container_name: ${INSTALL_NODE}-patroni
    hostname: ${INSTALL_NODE}
    restart: always
    network_mode: host
    environment:
      PGPORT: ${NODE_PORT_HOST}
      APIPORT: ${REST_PORT}
      SCOPE: ${SCOPE}

      SPILO_CONFIGURATION: |
        scope: ${SCOPE}

        restapi:
          listen: 0.0.0.0:${REST_PORT}
          connect_address: ${INSTALL_NODE_IP}:${REST_PORT}

        etcd:
          hosts:
            - ${NODE1_IP}:${ETCD_CLIENT_PORT}
            - ${NODE2_IP}:${ETCD_CLIENT_PORT}
            - ${NODE3_IP}:${ETCD_CLIENT_PORT}

        bootstrap:
          dcs:
            ttl: 30
            loop_wait: 10
            retry_timeout: 10
            postgresql:
              parameters:
                max_connections: 200
                shared_buffers: 1GB
                password_encryption: scram-sha-256
          initdb:
            - encoding: UTF8
            - data-checksums
          users:
            ${PG_SUPERUSER}:
              password: ${PG_SUPERPASS}
              options: [superuser, createdb, createrole]
            ${REPL_USER}:
              password: ${REPL_PASS}
              options: [replication]
            ${APP_USER}:
              password: ${APP_PASS}
              options: [login, createdb]

        postgresql:
          # ฟังบนพอร์ต node (เช่น 15432) เพื่อให้ HAProxy ต่อเข้าไป
          listen: 0.0.0.0:${NODE_PORT_HOST}
          connect_address: ${INSTALL_NODE_IP}:${NODE_PORT_HOST}
          data_dir: /home/postgres/pgdata/pgroot/data

          authentication:
            superuser:
              username: ${PG_SUPERUSER}
              password: ${PG_SUPERPASS}
            replication:
              username: ${REPL_USER}
              password: ${REPL_PASS}

          parameters:
            shared_preload_libraries: 'pg_stat_statements'

          pg_hba:
            - host replication ${REPL_USER} ${NODE_SUBNET} scram-sha-256
            - host all all ${NODE_SUBNET} scram-sha-256

    volumes:
      - /mnt/data/pgdb-${INSTALL_NODE}:/home/postgres/pgdata
    depends_on:
      - etcd

  haproxy:
    image: haproxy:2.8
    container_name: ${INSTALL_NODE}-haproxy
    restart: always
    network_mode: host
    command:
      - sh
      - -c
      - |
        set -e
        cat > /tmp/haproxy.cfg <<'EOF'
        global
            log stdout format raw local0
            maxconn 200
        defaults
            log global
            mode tcp
            timeout connect 10s
            timeout client 1m
            timeout server 1m
        frontend postgres
            bind *:5432
            default_backend pg_cluster
        backend pg_cluster
            option httpchk GET /primary
            http-check expect status 200
            server node1 ${NODE1_IP}:${NODE1_DB_PORT} check port ${REST_PORT} inter 1s rise 2 fall 2
            server node2 ${NODE2_IP}:${NODE2_DB_PORT} check port ${REST_PORT} inter 1s rise 2 fall 2
            server node3 ${NODE3_IP}:${NODE3_DB_PORT} check port ${REST_PORT} inter 1s rise 2 fall 2
        EOF
        exec /usr/local/sbin/haproxy -W -db -f /tmp/haproxy.cfg
    depends_on:
      - patroni

volumes:
  etcd_data: